# Required settings

DEFAULT_HISTORY_LEN = 200 # Number of tracks to go back to by default

# Update and move USER_OUTPUT_PATH to .secrets.toml if you'd rather not have it in version control
# OUTPUT_PATH = "/home/user"

# Optional settings
# none

# You will also need the following settings (again in .secrets.toml not here!)
# MY_API_KEY = "do"
# MY_API_SECRET = "not"
# MY_API_USER = "use"
# MY_API_PW_HASH = "these"
